server:
  port: 8083
spring:
  application:
    name: direction-service
  data:
    mongodb:
      database: directionDB
      port: 27017
      host: localhost
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true