server:
  port: 8084
spring:
  application:
    name: places-service
  data:
    mongodb:
      database: placesDB
      port: 27017
      host: localhost
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true